import { jsPDF } from "jspdf";
import type { AuditTransaction } from "./types";
import { KNOWN_MINTS } from "./constants";

function formatAmount(amount: bigint, mint: string): string {
  const info = KNOWN_MINTS[mint];
  if (!info) return `${amount.toString()} raw`;
  const divisor = BigInt(10 ** info.decimals);
  const whole = amount / divisor;
  const frac = (amount % divisor).toString().padStart(info.decimals, "0");
  return `${whole}.${frac.replace(/0+$/, "").padEnd(2, "0")} ${info.symbol}`;
}

export function generateAuditPdf(params: {
  daoAddress: string;
  auditorAddress: string;
  transactions: AuditTransaction[];
  generatedAt: Date;
}): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const { daoAddress, auditorAddress, transactions, generatedAt } = params;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Stealth — Confidential Payroll Audit Report", 20, 24);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`DAO: ${daoAddress}`, 20, 34);
  doc.text(`Auditor: ${auditorAddress}`, 20, 39);
  doc.text(`Generated: ${generatedAt.toISOString()}`, 20, 44);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");

  const tableTop = 54;
  const colWidths = [55, 25, 30, 25, 35];
  const headers = ["Signature", "Type", "Amount", "Token", "Timestamp"];
  let x = 20;
  headers.forEach((h, i) => {
    doc.text(h, x, tableTop);
    x += colWidths[i];
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);

  let y = tableTop + 6;
  for (const tx of transactions) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    const mintInfo = KNOWN_MINTS[tx.mint];
    const cols = [
      tx.signature.slice(0, 18) + "…",
      tx.type,
      formatAmount(tx.amount, tx.mint),
      mintInfo?.symbol ?? tx.mint.slice(0, 8),
      new Date(tx.timestamp).toISOString().slice(0, 10),
    ];
    let cx = 20;
    cols.forEach((c, i) => {
      doc.text(c, cx, y);
      cx += colWidths[i];
    });
    y += 5;
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Total transactions: ${transactions.length} | Generated by Stealth — Umbra Privacy SDK`,
    20,
    285
  );

  return doc.output("blob");
}
